### ISSUE TITLE
Feat: Add an extension from `ShadTheme.of(context)` into `context.shadTheme.textTheme`

### ISSUE THREAD

**Issue by moshOntong-IT** [nank1ro/flutter-shadcn-ui#140]
Is this possible? if it is then I can PR.

**Comment by moshOntong-IT** [comment]
https://github.com/nank1ro/flutter-shadcn-ui/pull/141

**Comment by nank1ro** [comment]
I don't think it makes sense to add the extensions.
Because then the code would be half and half using the extensions and not using them.
I think this is the onus is on the user, who can add them in his project as he likes.
Then there would really be a lot of extensions, I would do as Flutter does which does not provide them, so then the user can build them as they wish.
Let me know what you think
